### ISSUE TITLE
The while loop is causing 100% cpu usage

### ISSUE THREAD

**Issue by partofthething** [happyleavesaoc/gstreamer-player#4]
I experienced what a few people are seeing over at https://github.com/home-assistant/home-assistant/issues/7515 and tried the proposed fix of putting a `time.sleep(0.1)` call in the `while True` loop. It reduced cpu usage from 100% to 2%.

**Comment by partofthething** [comment]
To help close the homeassistant task, can we get a new release with this in it?

**Comment by happyleavesaoc** [comment]
@partofthething pushed `1.1.1` to pypi
